modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="colonyward"
version="${file.jarVersion}"
displayName="Colony Ward"
displayTest="IGNORE_ALL_VERSION"
logoFile="logo.png"
authors="Box.moe"
description="This mod prevent unwanted mobs from spawning inside colonies"

[[dependencies.colonyward]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.colonyward]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"

[[dependencies.colonyward]]
modId="minecolonies"
mandatory=true
versionRange="[1.19.2-1.0.1002-ALPHA,)"
ordering="AFTER"
side="BOTH"